// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/mgnx/scrape (interfaces: Scraper)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_scraper.go -package=mocks github.com/kdwils/mgnx/scrape Scraper
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scrape "github.com/kdwils/mgnx/scrape"
	gomock "go.uber.org/mock/gomock"
)

// MockScraper is a mock of Scraper interface.
type MockScraper struct {
	ctrl     *gomock.Controller
	recorder *MockScraperMockRecorder
	isgomock struct{}
}

// MockScraperMockRecorder is the mock recorder for MockScraper.
type MockScraperMockRecorder struct {
	mock *MockScraper
}

// NewMockScraper creates a new mock instance.
func NewMockScraper(ctrl *gomock.Controller) *MockScraper {
	mock := &MockScraper{ctrl: ctrl}
	mock.recorder = &MockScraperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScraper) EXPECT() *MockScraperMockRecorder {
	return m.recorder
}

// Scrape mocks base method.
func (m *MockScraper) Scrape(ctx context.Context, infohashes []string) ([]scrape.ScrapeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrape", ctx, infohashes)
	ret0, _ := ret[0].([]scrape.ScrapeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scrape indicates an expected call of Scrape.
func (mr *MockScraperMockRecorder) Scrape(ctx, infohashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrape", reflect.TypeOf((*MockScraper)(nil).Scrape), ctx, infohashes)
}
