// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/mgnx/dht/crawler (interfaces: DHT)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_dht.go -package=mocks github.com/kdwils/mgnx/dht/crawler DHT
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	reflect "reflect"

	krpc "github.com/kdwils/mgnx/dht/krpc"
	table "github.com/kdwils/mgnx/dht/table"
	types "github.com/kdwils/mgnx/dht/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDHT is a mock of DHT interface.
type MockDHT struct {
	ctrl     *gomock.Controller
	recorder *MockDHTMockRecorder
	isgomock struct{}
}

// MockDHTMockRecorder is the mock recorder for MockDHT.
type MockDHTMockRecorder struct {
	mock *MockDHT
}

// NewMockDHT creates a new mock instance.
func NewMockDHT(ctrl *gomock.Controller) *MockDHT {
	mock := &MockDHT{ctrl: ctrl}
	mock.recorder = &MockDHTMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDHT) EXPECT() *MockDHTMockRecorder {
	return m.recorder
}

// Closest mocks base method.
func (m *MockDHT) Closest(target table.NodeID, n int) []*table.Node {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Closest", target, n)
	ret0, _ := ret[0].([]*table.Node)
	return ret0
}

// Closest indicates an expected call of Closest.
func (mr *MockDHTMockRecorder) Closest(target, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Closest", reflect.TypeOf((*MockDHT)(nil).Closest), target, n)
}

// Emit mocks base method.
func (m *MockDHT) Emit(event types.DiscoveredPeers) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", event)
}

// Emit indicates an expected call of Emit.
func (mr *MockDHTMockRecorder) Emit(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockDHT)(nil).Emit), event)
}

// FindNode mocks base method.
func (m *MockDHT) FindNode(ctx context.Context, addr *net.UDPAddr, remoteID, target table.NodeID) (*krpc.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNode", ctx, addr, remoteID, target)
	ret0, _ := ret[0].(*krpc.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNode indicates an expected call of FindNode.
func (mr *MockDHTMockRecorder) FindNode(ctx, addr, remoteID, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNode", reflect.TypeOf((*MockDHT)(nil).FindNode), ctx, addr, remoteID, target)
}

// GetPeers mocks base method.
func (m *MockDHT) GetPeers(ctx context.Context, addr *net.UDPAddr, remoteID, infoHash table.NodeID) (*krpc.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeers", ctx, addr, remoteID, infoHash)
	ret0, _ := ret[0].(*krpc.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeers indicates an expected call of GetPeers.
func (mr *MockDHTMockRecorder) GetPeers(ctx, addr, remoteID, infoHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockDHT)(nil).GetPeers), ctx, addr, remoteID, infoHash)
}

// InsertNode mocks base method.
func (m *MockDHT) InsertNode(ctx context.Context, node *table.Node) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertNode", ctx, node)
}

// InsertNode indicates an expected call of InsertNode.
func (mr *MockDHTMockRecorder) InsertNode(ctx, node any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNode", reflect.TypeOf((*MockDHT)(nil).InsertNode), ctx, node)
}

// MarkFailure mocks base method.
func (m *MockDHT) MarkFailure(id table.NodeID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkFailure", id)
}

// MarkFailure indicates an expected call of MarkFailure.
func (mr *MockDHTMockRecorder) MarkFailure(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailure", reflect.TypeOf((*MockDHT)(nil).MarkFailure), id)
}

// MarkSuccess mocks base method.
func (m *MockDHT) MarkSuccess(id table.NodeID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkSuccess", id)
}

// MarkSuccess indicates an expected call of MarkSuccess.
func (mr *MockDHTMockRecorder) MarkSuccess(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSuccess", reflect.TypeOf((*MockDHT)(nil).MarkSuccess), id)
}

// NodeCount mocks base method.
func (m *MockDHT) NodeCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NodeCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// NodeCount indicates an expected call of NodeCount.
func (mr *MockDHTMockRecorder) NodeCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeCount", reflect.TypeOf((*MockDHT)(nil).NodeCount))
}

// SampleInfohashes mocks base method.
func (m *MockDHT) SampleInfohashes(ctx context.Context, addr *net.UDPAddr, remoteID, target table.NodeID) (*krpc.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleInfohashes", ctx, addr, remoteID, target)
	ret0, _ := ret[0].(*krpc.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SampleInfohashes indicates an expected call of SampleInfohashes.
func (mr *MockDHTMockRecorder) SampleInfohashes(ctx, addr, remoteID, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleInfohashes", reflect.TypeOf((*MockDHT)(nil).SampleInfohashes), ctx, addr, remoteID, target)
}
