// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kdwils/mgnx/dht (interfaces: Crawler)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_crawler.go -package=mocks github.com/kdwils/mgnx/dht Crawler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dht "github.com/kdwils/mgnx/dht"
	gomock "go.uber.org/mock/gomock"
)

// MockCrawler is a mock of Crawler interface.
type MockCrawler struct {
	ctrl     *gomock.Controller
	recorder *MockCrawlerMockRecorder
	isgomock struct{}
}

// MockCrawlerMockRecorder is the mock recorder for MockCrawler.
type MockCrawlerMockRecorder struct {
	mock *MockCrawler
}

// NewMockCrawler creates a new mock instance.
func NewMockCrawler(ctrl *gomock.Controller) *MockCrawler {
	mock := &MockCrawler{ctrl: ctrl}
	mock.recorder = &MockCrawlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrawler) EXPECT() *MockCrawlerMockRecorder {
	return m.recorder
}

// Infohashes mocks base method.
func (m *MockCrawler) Infohashes() <-chan dht.DiscoveredPeers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Infohashes")
	ret0, _ := ret[0].(<-chan dht.DiscoveredPeers)
	return ret0
}

// Infohashes indicates an expected call of Infohashes.
func (mr *MockCrawlerMockRecorder) Infohashes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infohashes", reflect.TypeOf((*MockCrawler)(nil).Infohashes))
}

// Start mocks base method.
func (m *MockCrawler) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCrawlerMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCrawler)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockCrawler) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockCrawlerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCrawler)(nil).Stop))
}
