package classify_test

import (
	"testing"

	"github.com/kdwils/mgnx/classify"
	"github.com/kdwils/mgnx/db/gen"
	"github.com/stretchr/testify/assert"
)

const mb = 1024 * 1024
const gb = 1024 * mb

const testMinSize = 50 * mb
const testMaxSize = 150 * gb

// testAllowed mirrors the default production allowlist used in tests.
var testAllowed = map[string]struct{}{
	".mkv": {}, ".mp4": {}, ".avi": {}, ".mov": {}, ".wmv": {}, ".m4v": {},
	".ts": {}, ".m2ts": {}, ".vob": {}, ".flv": {}, ".webm": {},
	".srt": {}, ".ass": {}, ".ssa": {}, ".sub": {},
}

func video(n int, sizeEach int64) []classify.File {
	files := make([]classify.File, n)
	for i := range files {
		files[i] = classify.File{Path: "video.mkv", Size: sizeEach}
	}
	return files
}

func TestClassify(t *testing.T) {
	tests := []struct {
		name                string
		torrent             string
		files               []classify.File
		totalSize           int64
		excludeAdultContent bool
		want                classify.Result
	}{
		{
			name:      "standard movie",
			torrent:   "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "The Dark Knight",
				Year:         2008,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "standard TV SxxExx",
			torrent:   "Breaking.Bad.S01E07.720p.BluRay.x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Breaking Bad",
				Season:       1,
				Episode:      7,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Breaking.Bad.S01E07.720p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV season pack",
			torrent:   "Game.of.Thrones.Season.3.1080p.BluRay.x264-GROUP",
			files:     video(10, 4*gb),
			totalSize: 40 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Game of Thrones",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Game.of.Thrones.Season.3.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV alternate NxM format",
			torrent:   "Seinfeld.5x12.The.Stall.DVDRip.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Seinfeld",
				Season:      5,
				Episode:     12,
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Seinfeld.5x12.The.Stall.DVDRip.x264",
			},
		},
		{
			name:      "TV S03 without episode",
			torrent:   "ShowName.S03.1080p.WEB-DL.HEVC.x265-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.S03.1080p.WEB-DL.HEVC.x265-GROUP",
			},
		},
		{
			name:      "TV season word lowercase",
			torrent:   "ShowName.season.3.1080p.WEB-DL.HEVC.x265-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.season.3.1080p.WEB-DL.HEVC.x265-GROUP",
			},
		},
		{
			name:      "TV underscore separator season complete",
			torrent:   "ShowName_Season_03_Complete_720p.HDTV.x264-GROUP",
			files:     video(10, 1*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "HDTV",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName_Season_03_Complete_720p.HDTV.x264-GROUP",
			},
		},
		{
			name:      "TV double digit season and episode",
			torrent:   "ShowName.S10E12.1080p.WEB-DL.AAC2.0.x264-GROUP",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       10,
				Episode:      12,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.S10E12.1080p.WEB-DL.AAC2.0.x264-GROUP",
			},
		},
		{
			name:      "TV underscore separator S01E02",
			torrent:   "ShowName_S01E02_1080p_WEB-DL_AAC2.0_x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       1,
				Episode:      2,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName_S01E02_1080p_WEB-DL_AAC2.0_x264-GROUP",
			},
		},
		{
			name:      "TV case insensitive s01e02",
			torrent:   "showname.s01e02.1080p.WEB-DL.AAC2.0.x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "showname",
				Season:       1,
				Episode:      2,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "showname.s01e02.1080p.WEB-DL.AAC2.0.x264-GROUP",
			},
		},
		{
			name:      "TV season 7 with group",
			torrent:   "ShowName.S07.1080p.WEB-DL.AAC2.0.x264-Group",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       7,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "Group",
				SceneName:    "ShowName.S07.1080p.WEB-DL.AAC2.0.x264-Group",
			},
		},
		{
			name:      "4K HDR movie",
			torrent:   "Avengers.Endgame.2019.2160p.UHD.BluRay.HDR.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Avengers Endgame",
				Year:         2019,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Avengers.Endgame.2019.2160p.UHD.BluRay.HDR.x265-GROUP",
			},
		},
		{
			name:      "WEB-DL TV episode",
			torrent:   "Succession.S04E03.1080p.WEB-DL.H.264-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Succession",
				Season:       4,
				Episode:      3,
				Quality:      "1080p",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Succession.S04E03.1080p.WEB-DL.H.264-GROUP",
			},
		},
		{
			name:      "single-file torrent with video extension",
			torrent:   "Interstellar.2014.1080p.BluRay.x264-GROUP.mkv",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Interstellar",
				Year:         2014,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Interstellar.2014.1080p.BluRay.x264-GROUP.mkv",
			},
		},
		{
			name:      "HDR10 dynamic range",
			torrent:   "Dune.2021.2160p.BluRay.HDR10.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Dune",
				Year:         2021,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR10",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Dune.2021.2160p.BluRay.HDR10.x265-GROUP",
			},
		},
		{
			name:      "underscore-separated name",
			torrent:   "The_Matrix_1999_1080p_BluRay_x264-GROUP",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "The Matrix",
				Year:         1999,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "The_Matrix_1999_1080p_BluRay_x264-GROUP",
			},
		},
		{
			name:      "movie without year",
			torrent:   "Pompeii.The.Secrets.of.Civita.Giuliana.1080p.HDTV.x264.AC3.MVGroup.org.mkv",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Pompeii The Secrets of Civita Giuliana",
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "HDTV",
				SceneName:   "Pompeii.The.Secrets.of.Civita.Giuliana.1080p.HDTV.x264.AC3.MVGroup.org.mkv",
			},
		},
		{
			name:      "rejected - no year or TV markers",
			torrent:   "Some.Random.Content.HDTV.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Some Random Content",
				Encoding:        "x264",
				Source:          "HDTV",
				SceneName:       "Some.Random.Content.HDTV.x264",
			},
		},
		{
			name:      "rejected - no video files",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     []classify.File{{Path: "readme.txt", Size: 1 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too small",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 10*mb),
			totalSize: 10 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too large",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 200*gb),
			totalSize: 200 * gb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:    "rejected - dominant bad extensions",
			torrent: "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			files: []classify.File{
				{Path: "file.mkv", Size: 1 * gb},
				{Path: "a.zip", Size: 100 * mb},
				{Path: "b.rar", Size: 100 * mb},
				{Path: "c.exe", Size: 100 * mb},
			},
			totalSize: 1300 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "bad_extension",
				Title:           "Some Pack",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV Episode keyword",
			torrent:   "The.Show.S01E01.Episode.Title.720p.WEB",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "The Show",
				Season:      1,
				Episode:     1,
				Quality:     "720p",
				Source:      "WEB",
				SceneName:   "The.Show.S01E01.Episode.Title.720p.WEB",
			},
		},
		{
			name:      "4K UHD",
			torrent:   "Movie.2020.2160p.UHD.BluRay.x265",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "2160p",
				Encoding:    "x265",
				Source:      "BluRay",
				SceneName:   "Movie.2020.2160p.UHD.BluRay.x265",
			},
		},
		{
			name:      "4K UHD HDR",
			torrent:   "Movie.2021.2160p.BluRay.HDR.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2021,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2021.2160p.BluRay.HDR.x265-GROUP",
			},
		},
		{
			name:      "Dolby Vision",
			torrent:   "Movie.2022.2160p.BluRay.Dolby.Vision.x264-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2022,
				Quality:      "2160p",
				Encoding:     "x264",
				DynamicRange: "Dolby Vision",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2022.2160p.BluRay.Dolby.Vision.x264-GROUP",
			},
		},
		{
			name:      "WEB-DL",
			torrent:   "Movie.2023.WEB-DL.1080p.x264",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2023,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "WEB-DL",
				SceneName:   "Movie.2023.WEB-DL.1080p.x264",
			},
		},
		{
			name:      "WEBRip",
			torrent:   "Movie.2023.WEBRip.720p.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2023,
				Quality:     "720p",
				Encoding:    "x264",
				Source:      "WEBRip",
				SceneName:   "Movie.2023.WEBRip.720p.x264",
			},
		},
		{
			name:      "multi-part release group",
			torrent:   "Show.2024.S01.1080p.WEB.H.264-CAKEDON",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Year:         2024,
				Season:       1,
				Quality:      "1080p",
				Source:       "WEB",
				ReleaseGroup: "CAKEDON",
				SceneName:    "Show.2024.S01.1080p.WEB.H.264-CAKEDON",
			},
		},
		{
			name:      "HEVC encoding",
			torrent:   "Movie.2020.1080p.BluRay.HEVC-EVO",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2020,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "BluRay",
				ReleaseGroup: "EVO",
				SceneName:    "Movie.2020.1080p.BluRay.HEVC-EVO",
			},
		},
		{
			name:      "AV1 encoding",
			torrent:   "Movie.2024.1080p.WEB.AV1-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2024,
				Quality:      "1080p",
				Encoding:     "AV1",
				Source:       "WEB",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2024.1080p.WEB.AV1-GROUP",
			},
		},
		{
			name:      "480p",
			torrent:   "Movie.2020.480p.DVDRip.x264",
			files:     video(1, 700*mb),
			totalSize: 700 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "480p",
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Movie.2020.480p.DVDRip.x264",
			},
		},
		{
			name:      "DVD",
			torrent:   "Movie.2005.DVD.x264",
			files:     video(1, 4*gb),
			totalSize: 4 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2005,
				Encoding:    "x264",
				Source:      "DVD",
				SceneName:   "Movie.2005.DVD.x264",
			},
		},
		{
			name:      "DVDRip",
			torrent:   "Movie.2005.DVDRip.XviD-LAM",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2005,
				Encoding:     "XviD",
				Source:       "DVDRip",
				ReleaseGroup: "LAM",
				SceneName:    "Movie.2005.DVDRip.XviD-LAM",
			},
		},
		{
			name:      "TV NxM format",
			torrent:   "Show.Name.5x12.720p.HDTV",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show Name",
				Season:      5,
				Episode:     12,
				Quality:     "720p",
				Source:      "HDTV",
				SceneName:   "Show.Name.5x12.720p.HDTV",
			},
		},
		{
			name:      "HDTV",
			torrent:   "Show.2024.S01E01.1080p.HDTV.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show",
				Year:        2024,
				Season:      1,
				Episode:     1,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "HDTV",
				SceneName:   "Show.2024.S01E01.1080p.HDTV.x264",
			},
		},
		{
			name:      "rejected - no year or TV markers",
			torrent:   "Some.Random.Content.HDTV.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Some Random Content",
				Encoding:        "x264",
				Source:          "HDTV",
				SceneName:       "Some.Random.Content.HDTV.x264",
			},
		},
		{
			name:      "rejected - no video files",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     []classify.File{{Path: "readme.txt", Size: 1 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too small",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 10*mb),
			totalSize: 10 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too large",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 200*gb),
			totalSize: 200 * gb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:    "rejected - dominant bad extensions",
			torrent: "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			files: []classify.File{
				{Path: "file.mkv", Size: 1 * gb},
				{Path: "a.zip", Size: 100 * mb},
				{Path: "b.rar", Size: 100 * mb},
				{Path: "c.exe", Size: 100 * mb},
			},
			totalSize: 1300 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "bad_extension",
				Title:           "Some Pack",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "only subtitle files",
			torrent:   "Movie.2020.1080p.BluRay",
			files:     []classify.File{{Path: "movie.srt", Size: 10 * 1024}},
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Source:          "BluRay",
				SceneName:       "Movie.2020.1080p.BluRay",
			},
		},
		{
			name:    "video with subtitles",
			torrent: "Movie.2020.1080p.BluRay.x264",
			files: []classify.File{
				{Path: "movie.mkv", Size: 2 * gb},
				{Path: "subs.srt", Size: 10 * 1024},
				{Path: "subs.eng.srt", Size: 10 * 1024},
			},
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "BluRay",
				SceneName:   "Movie.2020.1080p.BluRay.x264",
			},
		},
		{
			name:      "M2TS BluRay",
			torrent:   "Movie.2020.BDREMUX",
			files:     []classify.File{{Path: "movie.m2ts", Size: 30 * gb}},
			totalSize: 30 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Source:      "BDREMUX",
				SceneName:   "Movie.2020.BDREMUX",
			},
		},
		{
			name:      "TS transport stream",
			torrent:   "Show.S01E01.HDTV.ts",
			files:     []classify.File{{Path: "show.ts", Size: 2 * gb}},
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show",
				Season:      1,
				Episode:     1,
				Source:      "HDTV",
				SceneName:   "Show.S01E01.HDTV.ts",
			},
		},
		{
			name:      "multi-episode S01E01E02",
			torrent:   "Show.S02E03E04.1080p.WEB-DL.x264-GROUP",
			files:     video(2, 2*gb),
			totalSize: 4 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Season:       2,
				Episode:      3,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Show.S02E03E04.1080p.WEB-DL.x264-GROUP",
			},
		},
		{
			name:      "multi-episode range S01E01-E03",
			torrent:   "Show.S01E01-E03.720p.HDTV.x264-GROUP",
			files:     video(3, 1*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Season:       1,
				Episode:      1,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "HDTV",
				ReleaseGroup: "GROUP",
				SceneName:    "Show.S01E01-E03.720p.HDTV.x264-GROUP",
			},
		},
		{
			name:      "BDRemux before BluRay",
			torrent:   "Movie.2020.2160p.BDRemux.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2020,
				Quality:      "2160p",
				Encoding:     "x265",
				Source:       "BDRemux",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2020.2160p.BDRemux.x265-GROUP",
			},
		},
		{
			name:      "AV1 encoding not shadowed by AVC",
			torrent:   "Movie.2024.1080p.WEB.AV1-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2024,
				Quality:      "1080p",
				Encoding:     "AV1",
				Source:       "WEB",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2024.1080p.WEB.AV1-GROUP",
			},
		},
		{
			name:      "360p",
			torrent:   "Movie.2005.360p.DVDRip.x264",
			files:     video(1, 300*mb),
			totalSize: 300 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2005,
				Quality:     "360p",
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Movie.2005.360p.DVDRip.x264",
			},
		},
		{
			name:      "anime bracket prefix with absolute episode range",
			torrent:   "[Adosin] Bleach 168-189 (BD 1080p HEVC FLAC)",
			files:     video(22, 500*mb),
			totalSize: 11 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Bleach",
				Quality:     "1080p",
				Encoding:    "HEVC",
				SceneName:   "[Adosin] Bleach 168-189 (BD 1080p HEVC FLAC)",
			},
		},
		{
			name:      "anime bracket prefix with spacer episode format",
			torrent:   "[SubsPlease] Mushishi - 01 (1080p) [HASH]",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Mushishi",
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Mushishi - 01 (1080p) [HASH]",
			},
		},
		{
			name:      "anime bracket prefix with SxxExx",
			torrent:   "[SubsPlease] Attack on Titan S04E28 (1080p)",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Attack on Titan",
				Season:      4,
				Episode:     28,
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Attack on Titan S04E28 (1080p)",
			},
		},
		{
			name:      "anime bracket prefix with S2 - 01 episode notation",
			torrent:   "[SubsPlease] Tsue to Tsurugi no Wistoria S2 - 01 (1080p) [A88EE0BC].mkv",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Tsue to Tsurugi no Wistoria",
				Season:      2,
				Episode:     1,
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Tsue to Tsurugi no Wistoria S2 - 01 (1080p) [A88EE0BC].mkv",
			},
		},
		{
			name:      "anime Crunchyroll WEB-DL SxxExx",
			torrent:   "Frieren.S01E28.1080p.Crunchyroll.WEB-DL.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Frieren",
				Season:      1,
				Episode:     28,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "WEB-DL",
				SceneName:   "Frieren.S01E28.1080p.Crunchyroll.WEB-DL.x264",
			},
		},
		{
			name:                "adult content rejected when exclude_adult_content enabled",
			torrent:             "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "720p",
				Encoding:        "HEVC",
				Source:          "",
				ReleaseGroup:    "GRP",
				SceneName:       "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
				Title:           "SiteName 26 02 12 Some Performer XXX",
			},
		},
		{
			name:      "adult bracket-prefix release not misclassified as anime",
			torrent:   "[Brazzers] (Phoenix Marie, Richelle Ryan, Julia Ann) Cumming To America XXX (2016) (1080p HEVC) [GhostFreakXX]",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "[Brazzers] (Phoenix Marie, Richelle Ryan, Julia Ann) Cumming To America XXX",
				Year:        2016,
				Quality:     "1080p",
				Encoding:    "HEVC",
				SceneName:   "[Brazzers] (Phoenix Marie, Richelle Ryan, Julia Ann) Cumming To America XXX (2016) (1080p HEVC) [GhostFreakXX]",
			},
		},
		{
			name:                "adult bracket-prefix release rejected when exclude_adult_content enabled",
			torrent:             "[FemaleFakeTaxi] Rebecca M Welsh Lad Gets A Sweet Surprise XXX (2021) 1080p",
			files:               video(1, 500*mb),
			totalSize:           500 * mb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Title:           "[FemaleFakeTaxi] Rebecca M Welsh Lad Gets A Sweet Surprise XXX",
				Year:            2021,
				Quality:         "1080p",
				SceneName:       "[FemaleFakeTaxi] Rebecca M Welsh Lad Gets A Sweet Surprise XXX (2021) 1080p",
			},
		},
		{
			name:                "adult content rejected with XXXX",
			torrent:             "Some.Title.XXXX.1080p.WEB-DL-GROUP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "1080p",
				Source:          "WEB-DL",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Title.XXXX.1080p.WEB-DL-GROUP",
				Title:           "Some Title XXXX",
			},
		},
		{
			name:                "adult content not rejected with fewer than 3 X in a row",
			torrent:             "Some.Title.XX.1080p.WEB-DL-GROUP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Quality:      "1080p",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Some.Title.XX.1080p.WEB-DL-GROUP",
				Title:        "Some Title XX",
			},
		},
		{
			name:                "adult content allowed when exclude_adult_content disabled",
			torrent:             "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: false,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Quality:      "720p",
				Encoding:     "HEVC",
				Source:       "",
				ReleaseGroup: "GRP",
				SceneName:    "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
				Title:        "SiteName 26 02 12 Some Performer XXX",
			},
		},
		{
			name:                "adult studio name RealityKings rejected",
			torrent:             "RealityKings.26.02.12.Some.Performer.1080p.MP4-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "1080p",
				Encoding:        "",
				Source:          "",
				ReleaseGroup:    "GRP",
				SceneName:       "RealityKings.26.02.12.Some.Performer.1080p.MP4-GRP",
				Title:           "RealityKings 26 02 12 Some Performer",
			},
		},
		{
			name:      "zip file with anime bracket prefix not classified as anime",
			torrent:   "[GroupName] Some Manga Title [DL版].zip",
			files:     []classify.File{{Path: "content.zip", Size: 100 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "[GroupName] Some Manga Title [DL版] zip",
				SceneName:       "[GroupName] Some Manga Title [DL版].zip",
			},
		},
		{
			name:      "zip file with anime bracket prefix and year not classified as movie",
			torrent:   "[GroupName] Some Title 2024.zip",
			files:     []classify.File{{Path: "content.zip", Size: 100 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "[GroupName] Some Title",
				Year:            2024,
				SceneName:       "[GroupName] Some Title 2024.zip",
			},
		},
		{
			name:      "iso file classified as movie",
			torrent:   "Movie.2020.DVD.iso",
			files:     []classify.File{{Path: "movie.iso", Size: 4 * gb}},
			totalSize: 4 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Source:      "DVD",
				SceneName:   "Movie.2020.DVD.iso",
			},
		},
		{
			name:      "mpg file classified as movie",
			torrent:   "Movie.2005.DVDRip.mpg",
			files:     []classify.File{{Path: "movie.mpg", Size: 700 * mb}},
			totalSize: 700 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2005,
				Source:      "DVDRip",
				SceneName:   "Movie.2005.DVDRip.mpg",
			},
		},
		{
			name:      "www site prefix stripped - movie",
			torrent:   "www.UIndex.org    -    9.Ways.to.Hell.2022.1080p.WEB.H264-RVKD",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "9 Ways to Hell",
				Year:         2022,
				Quality:      "1080p",
				Encoding:     "H264",
				Source:       "WEB",
				ReleaseGroup: "RVKD",
				SceneName:    "www.UIndex.org    -    9.Ways.to.Hell.2022.1080p.WEB.H264-RVKD",
			},
		},
		{
			name:      "www site prefix stripped - tv SxxExx",
			torrent:   "www.UIndex.org    -    The Pitt S02E15 9 00 P M 2160p HMAX WEB-DL DDP5 1 Atmos DV HDR H 265-FLUX",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "The Pitt",
				Season:       2,
				Episode:      15,
				Quality:      "2160p",
				DynamicRange: "DV",
				Source:       "WEB-DL",
				ReleaseGroup: "FLUX",
				SceneName:    "www.UIndex.org    -    The Pitt S02E15 9 00 P M 2160p HMAX WEB-DL DDP5 1 Atmos DV HDR H 265-FLUX",
			},
		},
		{
			name:      "www site prefix stripped - tv different domain",
			torrent:   "www.Torrenting.com - Beauty in Black S01E03 2024 2160p NF WEB-DL DDP5 1 Atmos DV H 265-HHWEB",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Beauty in Black",
				Year:         2024,
				Season:       1,
				Episode:      3,
				Quality:      "2160p",
				DynamicRange: "DV",
				Source:       "WEB-DL",
				ReleaseGroup: "HHWEB",
				SceneName:    "www.Torrenting.com - Beauty in Black S01E03 2024 2160p NF WEB-DL DDP5 1 Atmos DV H 265-HHWEB",
			},
		},
		{
			name:      "anime EP absolute episode format",
			torrent:   "One.Piece.EP590.Historys.Strongest.Collaboration.vs.Glutton.of.the.Sea.1080p.NF.WEB-DL.DUAL.AAC2.0.H.264.ESub-ToonsHub.mkv",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeAnime,
				Title:        "One Piece",
				Episode:      590,
				Quality:      "1080p",
				Source:       "WEB-DL",
				ReleaseGroup: "ToonsHub",
				SceneName:    "One.Piece.EP590.Historys.Strongest.Collaboration.vs.Glutton.of.the.Sea.1080p.NF.WEB-DL.DUAL.AAC2.0.H.264.ESub-ToonsHub.mkv",
			},
		},
		{
			name:                "adult site name stepsiblingscaught rejected",
			torrent:             "stepsiblingscaught_fooling_around_with_my_step_brother_640.mp4",
			files:               []classify.File{{Path: "video.mp4", Size: 2 * gb}},
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "adult",
				Title:           "stepsiblingscaught fooling around with my step brother 640 mp4",
				SceneName:       "stepsiblingscaught_fooling_around_with_my_step_brother_640.mp4",
			},
		},
		{
			name:      "anime Yameii fansub with SxxExx title trim",
			torrent:   "[Yameii] Jujutsu Kaisen - S03E12 [English Dub] [CR WEB-DL 1080p H264 AAC] [339B079F].mkv",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Jujutsu Kaisen",
				Season:      3,
				Episode:     12,
				Quality:     "1080p",
				Encoding:    "H264",
				Source:      "WEB-DL",
				SceneName:   "[Yameii] Jujutsu Kaisen - S03E12 [English Dub] [CR WEB-DL 1080p H264 AAC] [339B079F].mkv",
			},
		},
		{
			name:      "anime DKB fansub with SxxExx title trim",
			torrent:   "[DKB] Mairimashita! Iruma-kun - S04E01 [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs][99BF25B0].mkv",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Mairimashita! Iruma-kun",
				Season:      4,
				Episode:     1,
				Quality:     "1080p",
				Encoding:    "HEVC",
				SceneName:   "[DKB] Mairimashita! Iruma-kun - S04E01 [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs][99BF25B0].mkv",
			},
		},
		{
			name:      "www site prefix stripped - tv with time-like episode title",
			torrent:   "www.UIndex.org    -    The Pitt S02E03 900 A M 2160p HMAX WEB-DL DDP5 1 DV HDR H 265-NTb",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "The Pitt",
				Season:       2,
				Episode:      3,
				Quality:      "2160p",
				DynamicRange: "DV",
				Source:       "WEB-DL",
				ReleaseGroup: "NTb",
				SceneName:    "www.UIndex.org    -    The Pitt S02E03 900 A M 2160p HMAX WEB-DL DDP5 1 DV HDR H 265-NTb",
			},
		},
		{
			name:                "WoodmanCastingX adult studio rejected",
			torrent:             "WoodmanCastingX - Victoria Pure - Casting W 175",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "adult",
				Title:           "WoodmanCastingX - Victoria Pure - Casting W 175",
				SceneName:       "WoodmanCastingX - Victoria Pure - Casting W 175",
			},
		},
		{
			name:      "tv with standalone codec number in name not falsely anime",
			torrent:   "Altered.Carbon.S01.WEBRip.264-PBS[ettv]",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Altered Carbon",
				Season:      1,
				Source:      "WEBRip",
				SceneName:   "Altered.Carbon.S01.WEBRip.264-PBS[ettv]",
			},
		},
		{
			name:      "movie with year range and numeric episode title not falsely anime",
			torrent:   "GHOST in the SHELL (1995-2015) - 3 Movies, COMPLETE Stand Alone Complex SERIES, Arise OVAs - 1080p DUAL Audio x264",
			files:     video(5, 10*gb),
			totalSize: 50 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "GHOST in the SHELL",
				Year:        1995,
				Quality:     "1080p",
				Encoding:    "x264",
				SceneName:   "GHOST in the SHELL (1995-2015) - 3 Movies, COMPLETE Stand Alone Complex SERIES, Arise OVAs - 1080p DUAL Audio x264",
			},
		},
		{
			name:      "tv SxxExx with time-like episode title not falsely anime",
			torrent:   "The Pitt S02E02 - 8.00 AM 4K DoVi-HDR HBO MAX WebDL H265 AC3 5.1.mkv",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "The Pitt",
				Season:       2,
				Episode:      2,
				Quality:      "4K",
				Encoding:     "H265",
				DynamicRange: "HDR",
				Source:       "WebDL",
				SceneName:    "The Pitt S02E02 - 8.00 AM 4K DoVi-HDR HBO MAX WebDL H265 AC3 5.1.mkv",
			},
		},
		{
			name:                "GoddessNudes adult site name rejected",
			torrent:             "GoddessNudes_2015_high",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Title:           "GoddessNudes",
				Year:            2015,
				SceneName:       "GoddessNudes_2015_high",
			},
		},
		{
			name:      "movie with trailing bracket tag not falsely anime",
			torrent:   "The.King.And.I.1956.Yul.Brynner.1080p.BluRay.H264.AAC.Mp4 [88]",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "The King And I",
				Year:        1956,
				Quality:     "1080p",
				Encoding:    "H264",
				Source:      "BluRay",
				SceneName:   "The.King.And.I.1956.Yul.Brynner.1080p.BluRay.H264.AAC.Mp4 [88]",
			},
		},
		{
			name:      "movie with foreign subtitle in name",
			torrent:   "Hook (El capitan Garfio) (1991) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.atomixHQ.com]",
			files:     video(1, 6*gb),
			totalSize: 6 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Hook (El capitan Garfio)",
				Year:        1991,
				Quality:     "720p",
				Encoding:    "X264",
				Source:      "BluRay",
				SceneName:   "Hook (El capitan Garfio) (1991) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.atomixHQ.com]",
			},
		},
		{
			name:      "TV XviD scene release",
			torrent:   "MythBusters.S08E21.Tablecloth.Chaos.HDTV.XviD-FQM",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "MythBusters",
				Season:       8,
				Episode:      21,
				Encoding:     "XviD",
				Source:       "HDTV",
				ReleaseGroup: "FQM",
				SceneName:    "MythBusters.S08E21.Tablecloth.Chaos.HDTV.XviD-FQM",
			},
		},
		{
			name:      "movie with YTS bracket tag not falsely anime",
			torrent:   "Three.Amigos.1986.1080p.BluRay.x264.AAC5.1-[YTS.MX] [88]",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Three Amigos",
				Year:        1986,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "BluRay",
				SceneName:   "Three.Amigos.1986.1080p.BluRay.x264.AAC5.1-[YTS.MX] [88]",
			},
		},
		{
			name:      "anime SubsPlease S3 - 01 spacer format",
			torrent:   "[SubsPlease] Enen no Shouboutai S3 - 01 (1080p) [695F5A4A].mkv",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Enen no Shouboutai",
				Season:      3,
				Episode:     1,
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Enen no Shouboutai S3 - 01 (1080p) [695F5A4A].mkv",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := classify.Classify(tc.torrent, tc.files, tc.totalSize, testMinSize, testMaxSize, testAllowed, true, tc.excludeAdultContent)
			assert.Equal(t, tc.want, got)
		})
	}
}
