package classify_test

import (
	"testing"

	"github.com/kdwils/mgnx/classify"
	"github.com/kdwils/mgnx/db/gen"
	"github.com/stretchr/testify/assert"
)

const mb = 1024 * 1024
const gb = 1024 * mb

const testMinSize = 50 * mb
const testMaxSize = 150 * gb

// testAllowed mirrors the default production allowlist used in tests.
var testAllowed = map[string]struct{}{
	".mkv": {}, ".mp4": {}, ".avi": {}, ".mov": {}, ".wmv": {}, ".m4v": {},
	".ts": {}, ".m2ts": {}, ".vob": {}, ".flv": {}, ".webm": {},
	".srt": {}, ".ass": {}, ".ssa": {}, ".sub": {},
}

func video(n int, sizeEach int64) []classify.File {
	files := make([]classify.File, n)
	for i := range files {
		files[i] = classify.File{Path: "video.mkv", Size: sizeEach}
	}
	return files
}

func TestClassify(t *testing.T) {
	tests := []struct {
		name                string
		torrent             string
		files               []classify.File
		totalSize           int64
		excludeAdultContent bool
		want                classify.Result
	}{
		{
			name:      "standard movie",
			torrent:   "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "The Dark Knight",
				Year:         2008,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "The.Dark.Knight.2008.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "standard TV SxxExx",
			torrent:   "Breaking.Bad.S01E07.720p.BluRay.x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Breaking Bad",
				Season:       1,
				Episode:      7,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Breaking.Bad.S01E07.720p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV season pack",
			torrent:   "Game.of.Thrones.Season.3.1080p.BluRay.x264-GROUP",
			files:     video(10, 4*gb),
			totalSize: 40 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Game of Thrones",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Game.of.Thrones.Season.3.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV alternate NxM format",
			torrent:   "Seinfeld.5x12.The.Stall.DVDRip.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Seinfeld",
				Season:      5,
				Episode:     12,
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Seinfeld.5x12.The.Stall.DVDRip.x264",
			},
		},
		{
			name:      "TV S03 without episode",
			torrent:   "ShowName.S03.1080p.WEB-DL.HEVC.x265-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.S03.1080p.WEB-DL.HEVC.x265-GROUP",
			},
		},
		{
			name:      "TV season word lowercase",
			torrent:   "ShowName.season.3.1080p.WEB-DL.HEVC.x265-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.season.3.1080p.WEB-DL.HEVC.x265-GROUP",
			},
		},
		{
			name:      "TV underscore separator season complete",
			torrent:   "ShowName_Season_03_Complete_720p.HDTV.x264-GROUP",
			files:     video(10, 1*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       3,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "HDTV",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName_Season_03_Complete_720p.HDTV.x264-GROUP",
			},
		},
		{
			name:      "TV double digit season and episode",
			torrent:   "ShowName.S10E12.1080p.WEB-DL.AAC2.0.x264-GROUP",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       10,
				Episode:      12,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName.S10E12.1080p.WEB-DL.AAC2.0.x264-GROUP",
			},
		},
		{
			name:      "TV underscore separator S01E02",
			torrent:   "ShowName_S01E02_1080p_WEB-DL_AAC2.0_x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       1,
				Episode:      2,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "ShowName_S01E02_1080p_WEB-DL_AAC2.0_x264-GROUP",
			},
		},
		{
			name:      "TV case insensitive s01e02",
			torrent:   "showname.s01e02.1080p.WEB-DL.AAC2.0.x264-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "showname",
				Season:       1,
				Episode:      2,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "showname.s01e02.1080p.WEB-DL.AAC2.0.x264-GROUP",
			},
		},
		{
			name:      "TV season 7 with group",
			torrent:   "ShowName.S07.1080p.WEB-DL.AAC2.0.x264-Group",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "ShowName",
				Season:       7,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "Group",
				SceneName:    "ShowName.S07.1080p.WEB-DL.AAC2.0.x264-Group",
			},
		},
		{
			name:      "4K HDR movie",
			torrent:   "Avengers.Endgame.2019.2160p.UHD.BluRay.HDR.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Avengers Endgame",
				Year:         2019,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Avengers.Endgame.2019.2160p.UHD.BluRay.HDR.x265-GROUP",
			},
		},
		{
			name:      "WEB-DL TV episode",
			torrent:   "Succession.S04E03.1080p.WEB-DL.H.264-GROUP",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Succession",
				Season:       4,
				Episode:      3,
				Quality:      "1080p",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Succession.S04E03.1080p.WEB-DL.H.264-GROUP",
			},
		},
		{
			name:      "single-file torrent with video extension",
			torrent:   "Interstellar.2014.1080p.BluRay.x264-GROUP.mkv",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Interstellar",
				Year:         2014,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Interstellar.2014.1080p.BluRay.x264-GROUP.mkv",
			},
		},
		{
			name:      "HDR10 dynamic range",
			torrent:   "Dune.2021.2160p.BluRay.HDR10.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Dune",
				Year:         2021,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR10",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Dune.2021.2160p.BluRay.HDR10.x265-GROUP",
			},
		},
		{
			name:      "underscore-separated name",
			torrent:   "The_Matrix_1999_1080p_BluRay_x264-GROUP",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "The Matrix",
				Year:         1999,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "The_Matrix_1999_1080p_BluRay_x264-GROUP",
			},
		},
		{
			name:      "movie without year",
			torrent:   "Pompeii.The.Secrets.of.Civita.Giuliana.1080p.HDTV.x264.AC3.MVGroup.org.mkv",
			files:     video(1, 8*gb),
			totalSize: 8 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Pompeii The Secrets of Civita Giuliana",
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "HDTV",
				SceneName:   "Pompeii.The.Secrets.of.Civita.Giuliana.1080p.HDTV.x264.AC3.MVGroup.org.mkv",
			},
		},
		{
			name:      "rejected - no year or TV markers",
			torrent:   "Some.Random.Content.HDTV.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Some Random Content",
				Encoding:        "x264",
				Source:          "HDTV",
				SceneName:       "Some.Random.Content.HDTV.x264",
			},
		},
		{
			name:      "rejected - no video files",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     []classify.File{{Path: "readme.txt", Size: 1 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "no_video",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too small",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 10*mb),
			totalSize: 10 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too large",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 200*gb),
			totalSize: 200 * gb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:    "rejected - dominant bad extensions",
			torrent: "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			files: []classify.File{
				{Path: "file.mkv", Size: 1 * gb},
				{Path: "a.zip", Size: 100 * mb},
				{Path: "b.rar", Size: 100 * mb},
				{Path: "c.exe", Size: 100 * mb},
			},
			totalSize: 1300 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "bad_extension",
				Title:           "Some Pack",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "TV Episode keyword",
			torrent:   "The.Show.S01E01.Episode.Title.720p.WEB",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "The Show",
				Season:      1,
				Episode:     1,
				Quality:     "720p",
				Source:      "WEB",
				SceneName:   "The.Show.S01E01.Episode.Title.720p.WEB",
			},
		},
		{
			name:      "4K UHD",
			torrent:   "Movie.2020.2160p.UHD.BluRay.x265",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "2160p",
				Encoding:    "x265",
				Source:      "BluRay",
				SceneName:   "Movie.2020.2160p.UHD.BluRay.x265",
			},
		},
		{
			name:      "4K UHD HDR",
			torrent:   "Movie.2021.2160p.BluRay.HDR.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2021,
				Quality:      "2160p",
				Encoding:     "x265",
				DynamicRange: "HDR",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2021.2160p.BluRay.HDR.x265-GROUP",
			},
		},
		{
			name:      "Dolby Vision",
			torrent:   "Movie.2022.2160p.BluRay.Dolby.Vision.x264-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2022,
				Quality:      "2160p",
				Encoding:     "x264",
				DynamicRange: "Dolby Vision",
				Source:       "BluRay",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2022.2160p.BluRay.Dolby.Vision.x264-GROUP",
			},
		},
		{
			name:      "WEB-DL",
			torrent:   "Movie.2023.WEB-DL.1080p.x264",
			files:     video(1, 2*gb),
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2023,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "WEB-DL",
				SceneName:   "Movie.2023.WEB-DL.1080p.x264",
			},
		},
		{
			name:      "WEBRip",
			torrent:   "Movie.2023.WEBRip.720p.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2023,
				Quality:     "720p",
				Encoding:    "x264",
				Source:      "WEBRip",
				SceneName:   "Movie.2023.WEBRip.720p.x264",
			},
		},
		{
			name:      "multi-part release group",
			torrent:   "Show.2024.S01.1080p.WEB.H.264-CAKEDON",
			files:     video(1, 3*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Year:         2024,
				Season:       1,
				Quality:      "1080p",
				Source:       "WEB",
				ReleaseGroup: "CAKEDON",
				SceneName:    "Show.2024.S01.1080p.WEB.H.264-CAKEDON",
			},
		},
		{
			name:      "HEVC encoding",
			torrent:   "Movie.2020.1080p.BluRay.HEVC-EVO",
			files:     video(1, 10*gb),
			totalSize: 10 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2020,
				Quality:      "1080p",
				Encoding:     "HEVC",
				Source:       "BluRay",
				ReleaseGroup: "EVO",
				SceneName:    "Movie.2020.1080p.BluRay.HEVC-EVO",
			},
		},
		{
			name:      "AV1 encoding",
			torrent:   "Movie.2024.1080p.WEB.AV1-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2024,
				Quality:      "1080p",
				Encoding:     "AV1",
				Source:       "WEB",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2024.1080p.WEB.AV1-GROUP",
			},
		},
		{
			name:      "480p",
			torrent:   "Movie.2020.480p.DVDRip.x264",
			files:     video(1, 700*mb),
			totalSize: 700 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "480p",
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Movie.2020.480p.DVDRip.x264",
			},
		},
		{
			name:      "DVD",
			torrent:   "Movie.2005.DVD.x264",
			files:     video(1, 4*gb),
			totalSize: 4 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2005,
				Encoding:    "x264",
				Source:      "DVD",
				SceneName:   "Movie.2005.DVD.x264",
			},
		},
		{
			name:      "DVDRip",
			torrent:   "Movie.2005.DVDRip.XviD-LAM",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2005,
				Encoding:     "XviD",
				Source:       "DVDRip",
				ReleaseGroup: "LAM",
				SceneName:    "Movie.2005.DVDRip.XviD-LAM",
			},
		},
		{
			name:      "TV NxM format",
			torrent:   "Show.Name.5x12.720p.HDTV",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show Name",
				Season:      5,
				Episode:     12,
				Quality:     "720p",
				Source:      "HDTV",
				SceneName:   "Show.Name.5x12.720p.HDTV",
			},
		},
		{
			name:      "HDTV",
			torrent:   "Show.2024.S01E01.1080p.HDTV.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show",
				Year:        2024,
				Season:      1,
				Episode:     1,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "HDTV",
				SceneName:   "Show.2024.S01E01.1080p.HDTV.x264",
			},
		},
		{
			name:      "rejected - no year or TV markers",
			torrent:   "Some.Random.Content.HDTV.x264",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeUnknown,
				RejectionReason: "unknown_type",
				Title:           "Some Random Content",
				Encoding:        "x264",
				Source:          "HDTV",
				SceneName:       "Some.Random.Content.HDTV.x264",
			},
		},
		{
			name:      "rejected - no video files",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     []classify.File{{Path: "readme.txt", Size: 1 * mb}},
			totalSize: 100 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "no_video",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too small",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 10*mb),
			totalSize: 10 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "rejected - too large",
			torrent:   "Movie.2020.1080p.BluRay.x264-GROUP",
			files:     video(1, 200*gb),
			totalSize: 200 * gb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "size",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Movie.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:    "rejected - dominant bad extensions",
			torrent: "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			files: []classify.File{
				{Path: "file.mkv", Size: 1 * gb},
				{Path: "a.zip", Size: 100 * mb},
				{Path: "b.rar", Size: 100 * mb},
				{Path: "c.exe", Size: 100 * mb},
			},
			totalSize: 1300 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "bad_extension",
				Title:           "Some Pack",
				Year:            2020,
				Quality:         "1080p",
				Encoding:        "x264",
				Source:          "BluRay",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Pack.2020.1080p.BluRay.x264-GROUP",
			},
		},
		{
			name:      "only subtitle files",
			torrent:   "Movie.2020.1080p.BluRay",
			files:     []classify.File{{Path: "movie.srt", Size: 10 * 1024}},
			totalSize: 500 * mb,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "no_video",
				Title:           "Movie",
				Year:            2020,
				Quality:         "1080p",
				Source:          "BluRay",
				SceneName:       "Movie.2020.1080p.BluRay",
			},
		},
		{
			name:    "video with subtitles",
			torrent: "Movie.2020.1080p.BluRay.x264",
			files: []classify.File{
				{Path: "movie.mkv", Size: 2 * gb},
				{Path: "subs.srt", Size: 10 * 1024},
				{Path: "subs.eng.srt", Size: 10 * 1024},
			},
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Quality:     "1080p",
				Encoding:    "x264",
				Source:      "BluRay",
				SceneName:   "Movie.2020.1080p.BluRay.x264",
			},
		},
		{
			name:      "M2TS BluRay",
			torrent:   "Movie.2020.BDREMUX",
			files:     []classify.File{{Path: "movie.m2ts", Size: 30 * gb}},
			totalSize: 30 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2020,
				Source:      "BDREMUX",
				SceneName:   "Movie.2020.BDREMUX",
			},
		},
		{
			name:      "TS transport stream",
			torrent:   "Show.S01E01.HDTV.ts",
			files:     []classify.File{{Path: "show.ts", Size: 2 * gb}},
			totalSize: 2 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeTv,
				Title:       "Show",
				Season:      1,
				Episode:     1,
				Source:      "HDTV",
				SceneName:   "Show.S01E01.HDTV.ts",
			},
		},
		{
			name:      "multi-episode S01E01E02",
			torrent:   "Show.S02E03E04.1080p.WEB-DL.x264-GROUP",
			files:     video(2, 2*gb),
			totalSize: 4 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Season:       2,
				Episode:      3,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Show.S02E03E04.1080p.WEB-DL.x264-GROUP",
			},
		},
		{
			name:      "multi-episode range S01E01-E03",
			torrent:   "Show.S01E01-E03.720p.HDTV.x264-GROUP",
			files:     video(3, 1*gb),
			totalSize: 3 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeTv,
				Title:        "Show",
				Season:       1,
				Episode:      1,
				Quality:      "720p",
				Encoding:     "x264",
				Source:       "HDTV",
				ReleaseGroup: "GROUP",
				SceneName:    "Show.S01E01-E03.720p.HDTV.x264-GROUP",
			},
		},
		{
			name:      "BDRemux before BluRay",
			torrent:   "Movie.2020.2160p.BDRemux.x265-GROUP",
			files:     video(1, 60*gb),
			totalSize: 60 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2020,
				Quality:      "2160p",
				Encoding:     "x265",
				Source:       "BDRemux",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2020.2160p.BDRemux.x265-GROUP",
			},
		},
		{
			name:      "AV1 encoding not shadowed by AVC",
			torrent:   "Movie.2024.1080p.WEB.AV1-GROUP",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Title:        "Movie",
				Year:         2024,
				Quality:      "1080p",
				Encoding:     "AV1",
				Source:       "WEB",
				ReleaseGroup: "GROUP",
				SceneName:    "Movie.2024.1080p.WEB.AV1-GROUP",
			},
		},
		{
			name:      "360p",
			torrent:   "Movie.2005.360p.DVDRip.x264",
			files:     video(1, 300*mb),
			totalSize: 300 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeMovie,
				Title:       "Movie",
				Year:        2005,
				Quality:     "360p",
				Encoding:    "x264",
				Source:      "DVDRip",
				SceneName:   "Movie.2005.360p.DVDRip.x264",
			},
		},
		{
			name:      "anime bracket prefix with absolute episode range",
			torrent:   "[Adosin] Bleach 168-189 (BD 1080p HEVC FLAC)",
			files:     video(22, 500*mb),
			totalSize: 11 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Bleach",
				Quality:     "1080p",
				Encoding:    "HEVC",
				SceneName:   "[Adosin] Bleach 168-189 (BD 1080p HEVC FLAC)",
			},
		},
		{
			name:      "anime bracket prefix with spacer episode format",
			torrent:   "[SubsPlease] Mushishi - 01 (1080p) [HASH]",
			files:     video(1, 500*mb),
			totalSize: 500 * mb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Mushishi",
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Mushishi - 01 (1080p) [HASH]",
			},
		},
		{
			name:      "anime bracket prefix with SxxExx",
			torrent:   "[SubsPlease] Attack on Titan S04E28 (1080p)",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Attack on Titan",
				Season:      4,
				Episode:     28,
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Attack on Titan S04E28 (1080p)",
			},
		},
		{
			name:      "anime bracket prefix with S2 - 01 episode notation",
			torrent:   "[SubsPlease] Tsue to Tsurugi no Wistoria S2 - 01 (1080p) [A88EE0BC].mkv",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:       gen.TorrentStateClassified,
				ContentType: gen.ContentTypeAnime,
				Title:       "Tsue to Tsurugi no Wistoria",
				Season:      2,
				Episode:     1,
				Quality:     "1080p",
				SceneName:   "[SubsPlease] Tsue to Tsurugi no Wistoria S2 - 01 (1080p) [A88EE0BC].mkv",
			},
		},
		{
			name:      "anime Crunchyroll WEB-DL SxxExx",
			torrent:   "Frieren.S01E28.1080p.Crunchyroll.WEB-DL.x264",
			files:     video(1, 1*gb),
			totalSize: 1 * gb,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeAnime,
				Title:        "Frieren",
				Season:       1,
				Episode:      28,
				Quality:      "1080p",
				Encoding:     "x264",
				Source:       "WEB-DL",
				SceneName:    "Frieren.S01E28.1080p.Crunchyroll.WEB-DL.x264",
			},
		},
		{
			name:                "adult content rejected when exclude_adult_content enabled",
			torrent:             "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "720p",
				Encoding:        "HEVC",
				Source:          "",
				ReleaseGroup:    "GRP",
				SceneName:       "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
				Title:           "SiteName 26 02 12 Some Performer XXX",
			},
		},
		{
			name:                "adult content rejected with XXXX",
			torrent:             "Some.Title.XXXX.1080p.WEB-DL-GROUP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "1080p",
				Source:          "WEB-DL",
				ReleaseGroup:    "GROUP",
				SceneName:       "Some.Title.XXXX.1080p.WEB-DL-GROUP",
				Title:           "Some Title XXXX",
			},
		},
		{
			name:                "adult content not rejected with fewer than 3 X in a row",
			torrent:             "Some.Title.XX.1080p.WEB-DL-GROUP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Quality:      "1080p",
				Source:       "WEB-DL",
				ReleaseGroup: "GROUP",
				SceneName:    "Some.Title.XX.1080p.WEB-DL-GROUP",
				Title:        "Some Title XX",
			},
		},
		{
			name:                "adult content allowed when exclude_adult_content disabled",
			torrent:             "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: false,
			want: classify.Result{
				State:        gen.TorrentStateClassified,
				ContentType:  gen.ContentTypeMovie,
				Quality:      "720p",
				Encoding:     "HEVC",
				Source:       "",
				ReleaseGroup: "GRP",
				SceneName:    "SiteName.26.02.12.Some.Performer.XXX.720p.HEVC.x265-GRP",
				Title:        "SiteName 26 02 12 Some Performer XXX",
			},
		},
		{
			name:                "adult studio name RealityKings rejected",
			torrent:             "RealityKings.26.02.12.Some.Performer.1080p.MP4-GRP",
			files:               video(1, 2*gb),
			totalSize:           2 * gb,
			excludeAdultContent: true,
			want: classify.Result{
				State:           gen.TorrentStateRejected,
				ContentType:     gen.ContentTypeMovie,
				RejectionReason: "adult",
				Quality:         "1080p",
				Encoding:        "",
				Source:          "",
				ReleaseGroup:    "GRP",
				SceneName:       "RealityKings.26.02.12.Some.Performer.1080p.MP4-GRP",
				Title:           "RealityKings 26 02 12 Some Performer",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := classify.Classify(tc.torrent, tc.files, tc.totalSize, testMinSize, testMaxSize, testAllowed, true, tc.excludeAdultContent)
			assert.Equal(t, tc.want, got)
		})
	}
}
