// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ContentType string

const (
	ContentTypeMovie   ContentType = "movie"
	ContentTypeTv      ContentType = "tv"
	ContentTypeUnknown ContentType = "unknown"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type TorrentState string

const (
	TorrentStatePending    TorrentState = "pending"
	TorrentStateClassified TorrentState = "classified"
	TorrentStateEnriched   TorrentState = "enriched"
	TorrentStateActive     TorrentState = "active"
	TorrentStateDead       TorrentState = "dead"
	TorrentStateRejected   TorrentState = "rejected"
)

func (e *TorrentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TorrentState(s)
	case string:
		*e = TorrentState(s)
	default:
		return fmt.Errorf("unsupported scan type for TorrentState: %T", src)
	}
	return nil
}

type NullTorrentState struct {
	TorrentState TorrentState `json:"torrent_state"`
	Valid        bool         `json:"valid"` // Valid is true if TorrentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTorrentState) Scan(value interface{}) error {
	if value == nil {
		ns.TorrentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TorrentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTorrentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TorrentState), nil
}

type Genre struct {
	ID        int64              `json:"id"`
	TmdbID    int32              `json:"tmdb_id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ScrapeHistory struct {
	ID        int64              `json:"id"`
	Infohash  string             `json:"infohash"`
	TrackerID int64              `json:"tracker_id"`
	ScrapedAt pgtype.Timestamptz `json:"scraped_at"`
	Seeders   int64              `json:"seeders"`
	Leechers  int64              `json:"leechers"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TmdbMovie struct {
	Infohash        string             `json:"infohash"`
	TmdbID          int64              `json:"tmdb_id"`
	ImdbID          pgtype.Text        `json:"imdb_id"`
	Title           string             `json:"title"`
	OriginalTitle   pgtype.Text        `json:"original_title"`
	Year            pgtype.Int4        `json:"year"`
	Overview        pgtype.Text        `json:"overview"`
	Runtime         pgtype.Int4        `json:"runtime"`
	Language        pgtype.Text        `json:"language"`
	Popularity      pgtype.Float8      `json:"popularity"`
	VoteAverage     pgtype.Float8      `json:"vote_average"`
	PosterPath      pgtype.Text        `json:"poster_path"`
	BackdropPath    pgtype.Text        `json:"backdrop_path"`
	MatchConfidence float64            `json:"match_confidence"`
	MatchedAt       pgtype.Timestamptz `json:"matched_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TmdbMovieGenre struct {
	Infohash string `json:"infohash"`
	GenreID  int64  `json:"genre_id"`
}

type TmdbTv struct {
	Infohash        string             `json:"infohash"`
	TmdbID          int64              `json:"tmdb_id"`
	ImdbID          pgtype.Text        `json:"imdb_id"`
	SeriesName      string             `json:"series_name"`
	Season          pgtype.Int4        `json:"season"`
	Episode         pgtype.Int4        `json:"episode"`
	EpisodeName     pgtype.Text        `json:"episode_name"`
	Overview        pgtype.Text        `json:"overview"`
	FirstAirDate    pgtype.Date        `json:"first_air_date"`
	MatchConfidence float64            `json:"match_confidence"`
	MatchedAt       pgtype.Timestamptz `json:"matched_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TmdbTvGenre struct {
	Infohash string `json:"infohash"`
	GenreID  int64  `json:"genre_id"`
}

type Torrent struct {
	Infohash                  string             `json:"infohash"`
	Name                      string             `json:"name"`
	TotalSize                 int64              `json:"total_size"`
	FileCount                 int64              `json:"file_count"`
	State                     TorrentState       `json:"state"`
	ContentType               ContentType        `json:"content_type"`
	Quality                   pgtype.Text        `json:"quality"`
	Encoding                  pgtype.Text        `json:"encoding"`
	DynamicRange              pgtype.Text        `json:"dynamic_range"`
	Source                    pgtype.Text        `json:"source"`
	ReleaseGroup              pgtype.Text        `json:"release_group"`
	SceneName                 pgtype.Text        `json:"scene_name"`
	Seeders                   int64              `json:"seeders"`
	Leechers                  int64              `json:"leechers"`
	ScrapeAt                  pgtype.Timestamptz `json:"scrape_at"`
	EnrichmentAttempts        int32              `json:"enrichment_attempts"`
	EnrichmentLastAttemptedAt pgtype.Timestamptz `json:"enrichment_last_attempted_at"`
	FirstSeen                 pgtype.Timestamptz `json:"first_seen"`
	LastSeen                  pgtype.Timestamptz `json:"last_seen"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type TorrentFile struct {
	ID        int64              `json:"id"`
	Infohash  string             `json:"infohash"`
	Path      string             `json:"path"`
	Size      int64              `json:"size"`
	Extension pgtype.Text        `json:"extension"`
	IsVideo   bool               `json:"is_video"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TorrentTracker struct {
	Infohash   string             `json:"infohash"`
	TrackerID  int64              `json:"tracker_id"`
	LastScrape pgtype.Timestamptz `json:"last_scrape"`
	IsActive   bool               `json:"is_active"`
}

type Tracker struct {
	ID        int64              `json:"id"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
