// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Fetch all active encodes of a specific movie by IMDB ID. Used for t=movie&imdbid=.
	GetMoviesByIMDB(ctx context.Context, imdbID pgtype.Text) ([]GetMoviesByIMDBRow, error)
	// Fetch TV torrents by IMDB ID, optionally filtered to season/episode. Used for t=tvsearch&imdbid=.
	GetTVByIMDB(ctx context.Context, arg GetTVByIMDBParams) ([]GetTVByIMDBRow, error)
	GetTorrentByInfohash(ctx context.Context, infohash string) (GetTorrentByInfohashRow, error)
	// General search across all active torrents. Used for t=search.
	SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error)
	// Search active movie torrents with enrichment data. Used for t=movie.
	SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]SearchMoviesRow, error)
	// Search active TV torrents with enrichment data. Used for t=tvsearch.
	SearchTV(ctx context.Context, arg SearchTVParams) ([]SearchTVRow, error)
}

var _ Querier = (*Queries)(nil)
