// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: torznab.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMoviesByIMDB = `-- name: GetMoviesByIMDB :many
SELECT
    t.infohash,
    t.name,
    t.total_size,
    t.file_count,
    t.quality,
    t.encoding,
    t.dynamic_range,
    t.source,
    t.release_group,
    t.seeders,
    t.leechers,
    t.first_seen,
    m.tmdb_id,
    m.imdb_id,
    m.title        AS movie_title,
    m.year,
    m.overview,
    m.runtime,
    m.vote_average,
    m.poster_path
FROM torrents t
JOIN tmdb_movies m ON m.infohash = t.infohash
WHERE t.state = 'active'
  AND m.imdb_id = $1
ORDER BY t.seeders DESC
`

type GetMoviesByIMDBRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	TmdbID       int64              `json:"tmdb_id"`
	ImdbID       pgtype.Text        `json:"imdb_id"`
	MovieTitle   string             `json:"movie_title"`
	Year         pgtype.Int4        `json:"year"`
	Overview     pgtype.Text        `json:"overview"`
	Runtime      pgtype.Int4        `json:"runtime"`
	VoteAverage  pgtype.Float8      `json:"vote_average"`
	PosterPath   pgtype.Text        `json:"poster_path"`
}

// Fetch all active encodes of a specific movie by IMDB ID. Used for t=movie&imdbid=.
func (q *Queries) GetMoviesByIMDB(ctx context.Context, imdbID pgtype.Text) ([]GetMoviesByIMDBRow, error) {
	rows, err := q.db.Query(ctx, getMoviesByIMDB, imdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMoviesByIMDBRow
	for rows.Next() {
		var i GetMoviesByIMDBRow
		if err := rows.Scan(
			&i.Infohash,
			&i.Name,
			&i.TotalSize,
			&i.FileCount,
			&i.Quality,
			&i.Encoding,
			&i.DynamicRange,
			&i.Source,
			&i.ReleaseGroup,
			&i.Seeders,
			&i.Leechers,
			&i.FirstSeen,
			&i.TmdbID,
			&i.ImdbID,
			&i.MovieTitle,
			&i.Year,
			&i.Overview,
			&i.Runtime,
			&i.VoteAverage,
			&i.PosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTVByIMDB = `-- name: GetTVByIMDB :many
SELECT
    t.infohash,
    t.name,
    t.total_size,
    t.file_count,
    t.quality,
    t.encoding,
    t.dynamic_range,
    t.source,
    t.release_group,
    t.seeders,
    t.leechers,
    t.first_seen,
    tv.tmdb_id,
    tv.imdb_id,
    tv.series_name,
    tv.season,
    tv.episode,
    tv.episode_name,
    tv.first_air_date
FROM torrents t
JOIN tmdb_tv tv ON tv.infohash = t.infohash
WHERE t.state = 'active'
  AND tv.imdb_id = $1
  AND ($2::int IS NULL OR tv.season = $2::int)
  AND ($3::int IS NULL OR tv.episode = $3::int)
ORDER BY t.seeders DESC
`

type GetTVByIMDBParams struct {
	ImdbID  pgtype.Text `json:"imdb_id"`
	Season  pgtype.Int4 `json:"season"`
	Episode pgtype.Int4 `json:"episode"`
}

type GetTVByIMDBRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	TmdbID       int64              `json:"tmdb_id"`
	ImdbID       pgtype.Text        `json:"imdb_id"`
	SeriesName   string             `json:"series_name"`
	Season       pgtype.Int4        `json:"season"`
	Episode      pgtype.Int4        `json:"episode"`
	EpisodeName  pgtype.Text        `json:"episode_name"`
	FirstAirDate pgtype.Date        `json:"first_air_date"`
}

// Fetch TV torrents by IMDB ID, optionally filtered to season/episode. Used for t=tvsearch&imdbid=.
func (q *Queries) GetTVByIMDB(ctx context.Context, arg GetTVByIMDBParams) ([]GetTVByIMDBRow, error) {
	rows, err := q.db.Query(ctx, getTVByIMDB, arg.ImdbID, arg.Season, arg.Episode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTVByIMDBRow
	for rows.Next() {
		var i GetTVByIMDBRow
		if err := rows.Scan(
			&i.Infohash,
			&i.Name,
			&i.TotalSize,
			&i.FileCount,
			&i.Quality,
			&i.Encoding,
			&i.DynamicRange,
			&i.Source,
			&i.ReleaseGroup,
			&i.Seeders,
			&i.Leechers,
			&i.FirstSeen,
			&i.TmdbID,
			&i.ImdbID,
			&i.SeriesName,
			&i.Season,
			&i.Episode,
			&i.EpisodeName,
			&i.FirstAirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTorrentByInfohash = `-- name: GetTorrentByInfohash :one
SELECT
    infohash,
    name,
    total_size,
    file_count,
    state,
    content_type,
    quality,
    encoding,
    dynamic_range,
    source,
    release_group,
    seeders,
    leechers,
    first_seen,
    created_at,
    updated_at
FROM torrents
WHERE infohash = $1
`

type GetTorrentByInfohashRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	State        TorrentState       `json:"state"`
	ContentType  ContentType        `json:"content_type"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTorrentByInfohash(ctx context.Context, infohash string) (GetTorrentByInfohashRow, error) {
	row := q.db.QueryRow(ctx, getTorrentByInfohash, infohash)
	var i GetTorrentByInfohashRow
	err := row.Scan(
		&i.Infohash,
		&i.Name,
		&i.TotalSize,
		&i.FileCount,
		&i.State,
		&i.ContentType,
		&i.Quality,
		&i.Encoding,
		&i.DynamicRange,
		&i.Source,
		&i.ReleaseGroup,
		&i.Seeders,
		&i.Leechers,
		&i.FirstSeen,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchAll = `-- name: SearchAll :many
SELECT
    t.infohash,
    t.name,
    t.total_size,
    t.file_count,
    t.content_type,
    t.quality,
    t.encoding,
    t.dynamic_range,
    t.source,
    t.release_group,
    t.seeders,
    t.leechers,
    t.first_seen
FROM torrents t
WHERE t.state = 'active'
  AND ($1::text IS NULL
       OR to_tsvector('english', t.name) @@ plainto_tsquery('english', $1::text))
ORDER BY t.seeders DESC
LIMIT $3
OFFSET $2
`

type SearchAllParams struct {
	Query      pgtype.Text `json:"query"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type SearchAllRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	ContentType  ContentType        `json:"content_type"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
}

// General search across all active torrents. Used for t=search.
func (q *Queries) SearchAll(ctx context.Context, arg SearchAllParams) ([]SearchAllRow, error) {
	rows, err := q.db.Query(ctx, searchAll, arg.Query, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllRow
	for rows.Next() {
		var i SearchAllRow
		if err := rows.Scan(
			&i.Infohash,
			&i.Name,
			&i.TotalSize,
			&i.FileCount,
			&i.ContentType,
			&i.Quality,
			&i.Encoding,
			&i.DynamicRange,
			&i.Source,
			&i.ReleaseGroup,
			&i.Seeders,
			&i.Leechers,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT
    t.infohash,
    t.name,
    t.total_size,
    t.file_count,
    t.quality,
    t.encoding,
    t.dynamic_range,
    t.source,
    t.release_group,
    t.seeders,
    t.leechers,
    t.first_seen,
    m.tmdb_id,
    m.imdb_id,
    m.title        AS movie_title,
    m.year,
    m.overview,
    m.runtime,
    m.vote_average,
    m.poster_path
FROM torrents t
JOIN tmdb_movies m ON m.infohash = t.infohash
WHERE t.state = 'active'
  AND ($1::text IS NULL
       OR to_tsvector('english', t.name) @@ plainto_tsquery('english', $1::text))
ORDER BY t.seeders DESC
LIMIT $3
OFFSET $2
`

type SearchMoviesParams struct {
	Query      pgtype.Text `json:"query"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type SearchMoviesRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	TmdbID       int64              `json:"tmdb_id"`
	ImdbID       pgtype.Text        `json:"imdb_id"`
	MovieTitle   string             `json:"movie_title"`
	Year         pgtype.Int4        `json:"year"`
	Overview     pgtype.Text        `json:"overview"`
	Runtime      pgtype.Int4        `json:"runtime"`
	VoteAverage  pgtype.Float8      `json:"vote_average"`
	PosterPath   pgtype.Text        `json:"poster_path"`
}

// Search active movie torrents with enrichment data. Used for t=movie.
func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]SearchMoviesRow, error) {
	rows, err := q.db.Query(ctx, searchMovies, arg.Query, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMoviesRow
	for rows.Next() {
		var i SearchMoviesRow
		if err := rows.Scan(
			&i.Infohash,
			&i.Name,
			&i.TotalSize,
			&i.FileCount,
			&i.Quality,
			&i.Encoding,
			&i.DynamicRange,
			&i.Source,
			&i.ReleaseGroup,
			&i.Seeders,
			&i.Leechers,
			&i.FirstSeen,
			&i.TmdbID,
			&i.ImdbID,
			&i.MovieTitle,
			&i.Year,
			&i.Overview,
			&i.Runtime,
			&i.VoteAverage,
			&i.PosterPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTV = `-- name: SearchTV :many
SELECT
    t.infohash,
    t.name,
    t.total_size,
    t.file_count,
    t.quality,
    t.encoding,
    t.dynamic_range,
    t.source,
    t.release_group,
    t.seeders,
    t.leechers,
    t.first_seen,
    tv.tmdb_id,
    tv.imdb_id,
    tv.series_name,
    tv.season,
    tv.episode,
    tv.episode_name,
    tv.first_air_date
FROM torrents t
JOIN tmdb_tv tv ON tv.infohash = t.infohash
WHERE t.state = 'active'
  AND ($1::text IS NULL
       OR to_tsvector('english', t.name) @@ plainto_tsquery('english', $1::text))
  AND ($2::int IS NULL OR tv.season = $2::int)
  AND ($3::int IS NULL OR tv.episode = $3::int)
ORDER BY t.seeders DESC
LIMIT $5
OFFSET $4
`

type SearchTVParams struct {
	Query      pgtype.Text `json:"query"`
	Season     pgtype.Int4 `json:"season"`
	Episode    pgtype.Int4 `json:"episode"`
	PageOffset int32       `json:"page_offset"`
	PageSize   int32       `json:"page_size"`
}

type SearchTVRow struct {
	Infohash     string             `json:"infohash"`
	Name         string             `json:"name"`
	TotalSize    int64              `json:"total_size"`
	FileCount    int64              `json:"file_count"`
	Quality      pgtype.Text        `json:"quality"`
	Encoding     pgtype.Text        `json:"encoding"`
	DynamicRange pgtype.Text        `json:"dynamic_range"`
	Source       pgtype.Text        `json:"source"`
	ReleaseGroup pgtype.Text        `json:"release_group"`
	Seeders      int64              `json:"seeders"`
	Leechers     int64              `json:"leechers"`
	FirstSeen    pgtype.Timestamptz `json:"first_seen"`
	TmdbID       int64              `json:"tmdb_id"`
	ImdbID       pgtype.Text        `json:"imdb_id"`
	SeriesName   string             `json:"series_name"`
	Season       pgtype.Int4        `json:"season"`
	Episode      pgtype.Int4        `json:"episode"`
	EpisodeName  pgtype.Text        `json:"episode_name"`
	FirstAirDate pgtype.Date        `json:"first_air_date"`
}

// Search active TV torrents with enrichment data. Used for t=tvsearch.
func (q *Queries) SearchTV(ctx context.Context, arg SearchTVParams) ([]SearchTVRow, error) {
	rows, err := q.db.Query(ctx, searchTV,
		arg.Query,
		arg.Season,
		arg.Episode,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTVRow
	for rows.Next() {
		var i SearchTVRow
		if err := rows.Scan(
			&i.Infohash,
			&i.Name,
			&i.TotalSize,
			&i.FileCount,
			&i.Quality,
			&i.Encoding,
			&i.DynamicRange,
			&i.Source,
			&i.ReleaseGroup,
			&i.Seeders,
			&i.Leechers,
			&i.FirstSeen,
			&i.TmdbID,
			&i.ImdbID,
			&i.SeriesName,
			&i.Season,
			&i.Episode,
			&i.EpisodeName,
			&i.FirstAirDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
